CREATE TABLE import_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fonte VARCHAR(40) NOT NULL,
    escopo VARCHAR(100) NOT NULL,
    incremental_base BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL,
    requisicao TEXT NOT NULL,
    cursor_json TEXT,
    cache_json TEXT NOT NULL DEFAULT '{}',
    maximo_paginas INTEGER NOT NULL CHECK (maximo_paginas > 0),
    paginas INTEGER NOT NULL DEFAULT 0,
    recebidos BIGINT NOT NULL DEFAULT 0,
    processados BIGINT NOT NULL DEFAULT 0,
    erros BIGINT NOT NULL DEFAULT 0,
    ultima_carga BIGINT REFERENCES carga_dados(id_carga),
    mensagem TEXT,
    criado_em TIMESTAMPTZ NOT NULL,
    atualizado_em TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_import_job_pending ON import_job(atualizado_em, id)
    WHERE status IN ('PENDENTE', 'EM_EXECUCAO');
-- Also serialize failed resumable jobs: start a new job only after finishing
-- the existing one, to avoid competing snapshots for the same source.
CREATE UNIQUE INDEX uq_import_job_active_scope ON import_job(escopo)
    WHERE status IN ('PENDENTE', 'EM_EXECUCAO', 'FALHA', 'LIMITE_ATINGIDO');
