ALTER TABLE import_job ADD COLUMN ate_esgotar BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE import_job ADD COLUMN bootstrap_completo BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE import_job ALTER COLUMN paginas TYPE BIGINT;
